name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'client/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Client Dependencies
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-

      - name: Build Client
        run: |
          cd client
          echo -e "VITE_BACKEND_BASE_URL=${{ secrets.VITE_BACKEND_BASE_URL }}" > .env
          npm ci
          npm run build

      - name: Clean and Prepare Remote Client Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/e360consult/client/dist
            mkdir -p /home/ubuntu/e360consult/client/

      - name: Deploy Client Build Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "client/dist/*"
          target: "/home/ubuntu/e360consult/client/dist/"
          strip_components: 2

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'server/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Server Dependencies
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Install and Build Server
        run: |
          cd server
          npm ci
          npm run build
          if [ -d "dist/server/dist" ]; then
            mv dist/server/dist/* dist/
            rm -rf dist/server
          fi

      - name: Clean and Prepare Remote Server Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/e360consult/server
            mkdir -p /home/ubuntu/e360consult/server

      - name: Deploy Server Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "server/dist/*, server/package*.json"
          target: "/home/ubuntu/e360consult/server/"
          strip_components: 1

      - name: Install Server Dependencies on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/e360consult/server
            npm ci --production

      - name: Restart PM2 Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/e360consult
            pm2 reload ecosystem.config.js --only e360-consult
