# .github/workflows/deploy-server.yml
name: Deploy Server to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Cache Server Dependencies
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Install and Build Server
        run: |
          cd server
          # Create .env file with necessary environment variables
          echo -e "NODE_ENV=production" > .env
          echo -e "PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo -e "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo -e "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          # Add other environment variables as needed
          
          npm ci
          npm run build
          # Handle potential nested dist folders
          if [ -d "dist/server/dist" ]; then
            mv dist/server/dist/* dist/
            rm -rf dist/server
          fi
          
          # Manually copy templates
          mkdir -p dist/services/emails/templates
          cp -r src/services/emails/templates/* dist/services/emails/templates/
          # Verify templates were copied
          echo "Template files copied:"
          find dist/services/emails/templates -type f | wc -l

      - name: Clean and Prepare Remote Server Directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/e360consult/e360-main/server-new
            rm -rf /home/ubuntu/e360consult/e360-main/server-old

      - name: Deploy Server Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "server/dist/, server/package*.json, server/.env"
          target: "/home/ubuntu/e360consult/e360-main/server-new/"
          strip_components: 1
          concurrency: 10  # Increase concurrency for faster file transfer

      - name: Install Dependencies and Restart PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/e360consult/e360-main/server-new
            npm ci --production --no-audit --prefer-offline
            
            # Setup PM2 config if needed
            cd /home/ubuntu/e360consult/e360-main/
            if [ ! -f "ecosystem.config.js" ]; then
              echo "Creating PM2 ecosystem config file"
              echo 'module.exports = {
                apps: [{
                  name: "e360-consult",
                  script: "server/dist/index.js",
                  env: {
                    NODE_ENV: "production",
                  },
                  watch: false,
                  max_memory_restart: "300M"
                }]
              }' > ecosystem.config.js
            fi
            
            # Swap directories and restart app
            if [ -d "/home/ubuntu/e360consult/e360-main/server" ]; then
              mv /home/ubuntu/e360consult/e360-main/server /home/ubuntu/e360consult/e360-main/server-old
            fi
            mv /home/ubuntu/e360consult/e360-main/server-new /home/ubuntu/e360consult/e360-main/server
            sudo chown -R ubuntu:ubuntu /home/ubuntu/e360consult/e360-main/server
            
            # Restart the application
            pm2 reload ecosystem.config.js --only e360-consult
            
            # Clean up old directory after successful deployment
            rm -rf /home/ubuntu/e360consult/e360-main/server-old